language: java
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  - echo "deb http://repos.mesosphere.io/ubuntu/ precise main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
  - sudo apt-get update -qq
  - sudo apt-get install mesos
sudo: required
env:
  global:
    - MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
  matrix:
    - TEST_DIR=scheduler TEST_CMD='lein test :all'
    - TEST_DIR=jobclient TEST_CMD='mvn test'
script: cd $TEST_DIR && $TEST_CMD
